apiVersion: v1
name: serving
version: 0.3.5
kubeVersion: ">=1.18.0"
description: "Knative Serving"
sources:
- https://github.com/knative/serving
maintainers:
- name: chhsia0
- name: gilbert88
appVersion: "v0.18.3"
