# Default values for controllermanager.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

annotations: {}
replicaCount: 2
repository: quay.io/kubernetes-multicluster
image: kubefed
tag: canary
logLevel: 2
imagePullPolicy: IfNotPresent
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 64Mi
clusterAvailableDelay:
clusterUnavailableDelay:
leaderElectLeaseDuration:
leaderElectRenewDeadline:
leaderElectRetryPeriod:
clusterHealthCheckPeriod:
clusterHealthCheckFailureThreshold:
clusterHealthCheckSuccessThreshold:
clusterHealthCheckTimeout:
## Supported options are `configmaps` and `endpoints`
leaderElectResourceLock:
syncController:
  adoptResources:
## Value of feature gates item should be either `Enabled` or `Disabled`
featureGates:
  PushReconciler:
  SchedulerPreferences:
  CrossClusterServiceDiscovery:
  FederatedIngress:

certManager:
  enabled: false

webhook:
  annotations: {}
  repository: quay.io/kubernetes-multicluster
  image: kubefed
  tag: canary
  imagePullPolicy: IfNotPresent
  logLevel: 8
  env: {}
  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 64Mi
