apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubefed-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    kubefed-control-plane: controller-manager
{{- if .Values.annotations }}
  annotations:
{{ toYaml .Values.annotations | indent 4 }}
{{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      kubefed-control-plane: controller-manager
  strategy: {}
  template:
    metadata:
      labels:
        kubefed-control-plane: controller-manager
    spec:
      securityContext:
        runAsUser: 1001
      serviceAccountName: kubefed-controller
      containers:
      - command:
        - /hyperfed/controller-manager
        - "--v={{ .Values.logLevel }}"
        image: "{{ .Values.repository }}/{{ .Values.image }}:{{ .Values.tag }}"
        imagePullPolicy: "{{ .Values.imagePullPolicy }}"
        name: controller-manager
{{- if .Values.env }}
        env:
{{- range $key, $value := .Values.env }}
          - name: "{{ $key }}"
            value: "{{ $value }}"
{{- end }}
{{- end }}
        ports:
        - containerPort: 9090
          name: metrics
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 3
          timeoutSeconds: 3
        resources:
{{- if .Values.resources }}
{{ toYaml .Values.resources | indent 12 }}
{{- end }}
      terminationGracePeriodSeconds: 10
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: kubefed-admission-webhook
  labels:
    kubefed-admission-webhook: "true"
{{- if .Values.webhook.annotations }}
  annotations:
{{ toYaml .Values.webhook.annotations | indent 4 }}
{{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      kubefed-admission-webhook: "true"
  template:
    metadata:
      labels:
        kubefed-admission-webhook: "true"
    spec:
      securityContext:
        runAsUser: 1001
      serviceAccountName: kubefed-admission-webhook
      containers:
      - name: admission-webhook
        image: "{{ .Values.webhook.repository }}/{{ .Values.webhook.image }}:{{ .Values.webhook.tag }}"
        imagePullPolicy: "{{ .Values.webhook.imagePullPolicy }}"
{{- if .Values.webhook.env }}
        env:
{{- range $key, $value := .Values.webhook.env }}
          - name: "{{ $key }}"
            value: "{{ $value }}"
{{- end }}
{{- end }}
        command:
        - "/hyperfed/webhook"
        - "--secure-port=8443"
        - "--cert-dir=/var/serving-cert/"
        - "--v={{ .Values.webhook.logLevel }}"
        ports:
        - containerPort: 8443
        volumeMounts:
        - mountPath: /var/serving-cert
          name: serving-cert
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8443
            scheme: HTTPS
        resources:
{{- if .Values.webhook.resources }}
{{ toYaml .Values.webhook.resources | indent 12 }}
{{- end }}
      volumes:
      - name: serving-cert
        secret:
          defaultMode: 420
          secretName: kubefed-admission-webhook-serving-cert
