dependencies:

  - name: prometheus-operator
    version: 8.3.*
    repository: https://mesosphere.github.io/charts/staging/
    condition: prometheus-operator.enabled

  - name: thanos
    version: 0.3.*
    repository: https://kubernetes-charts.banzaicloud.com/
    condition: thanos.enabled
